// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantManagementApp.DbService.AppDbContextModels;

#nullable disable

namespace RestaurantManagementApp.DbService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250520133515_RemoveKey")]
    partial class RemoveKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RestaurantManagementApp.DbService.Tables.TblCategory", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CategoryId");

                    b.ToTable("TblCategories");
                });

            modelBuilder.Entity("RestaurantManagementApp.DbService.Tables.TblCustomizeOption", b =>
                {
                    b.Property<Guid>("CustomizeOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("CustomizeOptionId");

                    b.ToTable("TblCustomizeOptions");
                });

            modelBuilder.Entity("RestaurantManagementApp.DbService.Tables.TblMenuItem", b =>
                {
                    b.Property<Guid>("MenuItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MenuItemName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("MenuItemId");

                    b.HasIndex("CategoryId");

                    b.ToTable("TblMenuItems");
                });

            modelBuilder.Entity("RestaurantManagementApp.DbService.Tables.TblMenuItemCustomizeOption", b =>
                {
                    b.Property<Guid>("MenuItemCustomizeOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CustomizeOptionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MenuItemId")
                        .HasColumnType("char(36)");

                    b.HasKey("MenuItemCustomizeOptionId");

                    b.HasIndex("CustomizeOptionId");

                    b.HasIndex("MenuItemId");

                    b.ToTable("TblMenuItemCustomizeOptions");
                });

            modelBuilder.Entity("RestaurantManagementApp.DbService.Tables.TblMenuItem", b =>
                {
                    b.HasOne("RestaurantManagementApp.DbService.Tables.TblCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RestaurantManagementApp.DbService.Tables.TblMenuItemCustomizeOption", b =>
                {
                    b.HasOne("RestaurantManagementApp.DbService.Tables.TblCustomizeOption", "CustomizeOption")
                        .WithMany("MenuItemCustomizeOptions")
                        .HasForeignKey("CustomizeOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantManagementApp.DbService.Tables.TblMenuItem", "MenuItem")
                        .WithMany("MenuItemCustomizeOptions")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomizeOption");

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("RestaurantManagementApp.DbService.Tables.TblCustomizeOption", b =>
                {
                    b.Navigation("MenuItemCustomizeOptions");
                });

            modelBuilder.Entity("RestaurantManagementApp.DbService.Tables.TblMenuItem", b =>
                {
                    b.Navigation("MenuItemCustomizeOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
